# Generated by Django 3.0.1 on 2020-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('cname', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('program', models.CharField(choices=[('bs', 'BS'), ('mcs', 'MCS')], default='bs', max_length=3)),
                ('cnic', models.CharField(max_length=15)),
                ('challan_number', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('challan_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'UnPaid')], default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('degree_choice', models.CharField(choices=[('bs', 'BS'), ('mcs', 'MCS')], default='null', max_length=3)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images')),
                ('cname', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('degree_choice', models.CharField(choices=[('bs', 'BS'), ('mcs', 'MCS')], default='bs', max_length=3)),
                ('cnic', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('ptcl', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Khyber_Pakhtunkhwa', 'Khyber_Pakhtunkhwa'), ('Sindh', 'Sindh'), ('Balochistan', 'Balochistan')], default='null', max_length=30)),
                ('city', models.CharField(choices=[('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Faisalabad', 'Faisalabad'), ('Gujranwala', 'Gujranwala'), ('Rawalpindi', 'Rawalpindi'), ('Sargodha', 'Sargodha'), ('Bahawalpur', 'Bahawalpur'), ('Sialkot', 'Sialkot'), ('Sheikhupura', 'Sheikhupura'), ('Gujrat', 'Gujrat'), ('Jhang', 'Jhang'), ('Sahiwal', 'Sahiwal'), ('Peshawar', 'Peshawar'), ('Abbottabad', 'Abbottabad')], default='null', max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6)),
                ('math', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='null', max_length=4)),
                ('phystat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=4)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('check', models.CharField(choices=[('true', 'TRUE'), ('false', 'FALSE')], default='false', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_ID', models.CharField(max_length=50)),
                ('shifts', models.CharField(choices=[('1st group', '1st GROUP'), ('2nd group', '2nd GROUP'), ('3rd group', '3rd GROUP'), ('4th group', '4th GROUP'), ('5th group', '5th GROUP')], default='null', max_length=10)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('center', models.CharField(max_length=200)),
                ('hall_no', models.CharField(max_length=20)),
                ('seat_no', models.CharField(max_length=20)),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
