# Generated by Django 3.0.1 on 2020-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0003_auto_20200513_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
