# Generated by Django 3.0.1 on 2020-05-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0004_auto_20200513_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slip',
            name='slip_image',
        ),
    ]
