# Generated by Django 3.0.1 on 2020-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0005_remove_slip_slip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='cname',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='slip',
            name='cnic',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='slip',
            name='father_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='slip',
            name='program',
            field=models.CharField(choices=[('bs', 'BS'), ('mcs', 'MCS')], default='bs', max_length=3),
        ),
    ]
