# Generated by Django 3.0.1 on 2020-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0006_auto_20200513_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='cname',
            field=models.CharField(max_length=50),
        ),
    ]
