# Generated by Django 3.0.1 on 2020-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0008_auto_20200513_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='Roll_No',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='slip',
            name='user_name',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='slip',
            name='Form_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
