# Generated by Django 3.0.1 on 2020-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0010_auto_20200513_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='Slip_Show',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'NO')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='slip',
            name='program',
            field=models.CharField(choices=[('bs', 'BS'), ('mcs', 'MCS')], default='', max_length=3),
        ),
    ]
