# Generated by Django 3.0.1 on 2020-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0011_auto_20200514_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='shifts',
            field=models.CharField(choices=[('1st Group', '1st GROUP'), ('2nd Group', '2nd GROUP'), ('3rd Group', '3rd GROUP'), ('4th Group', '4th GROUP'), ('5th Group', '5th GROUP')], default='null', max_length=10),
        ),
    ]
