# Generated by Django 3.0.1 on 2020-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0012_auto_20200514_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='Image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
