# Generated by Django 3.0.1 on 2020-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0013_slip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='Image_url',
            field=models.CharField(max_length=500),
        ),
    ]
