# Generated by Django 3.0.1 on 2020-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0015_auto_20200514_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='Image_url',
            field=models.CharField(max_length=150),
        ),
    ]
