# Generated by Django 3.0.1 on 2020-05-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0017_slip_challan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slip',
            name='challan_number',
        ),
    ]
