# Generated by Django 3.0.1 on 2020-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0018_remove_slip_challan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='challan_number',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
